REM INSERTING into LOG_LEVEL
SET DEFINE OFF;
Insert into LOG_LEVEL (LOG_LEVEL,LOG_LEVEL_NO,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,LOV_LEVEL_NAME) values ('CRITICAL','50','FFA_CTL',to_date('26.03.20','DD.MM.RR'),'FFA_CTL',to_date('19.02.21','DD.MM.RR'),'Критический');
Insert into LOG_LEVEL (LOG_LEVEL,LOG_LEVEL_NO,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,LOV_LEVEL_NAME) values ('ERROR','40','FFA_CTL',to_date('26.03.20','DD.MM.RR'),'FFA_CTL',to_date('19.02.21','DD.MM.RR'),'Ошибка');
Insert into LOG_LEVEL (LOG_LEVEL,LOG_LEVEL_NO,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,LOV_LEVEL_NAME) values ('WARNING','30','FFA_CTL',to_date('26.03.20','DD.MM.RR'),'FFA_CTL',to_date('19.02.21','DD.MM.RR'),'Предупреждение');
Insert into LOG_LEVEL (LOG_LEVEL,LOG_LEVEL_NO,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,LOV_LEVEL_NAME) values ('INFO','20','FFA_CTL',to_date('26.03.20','DD.MM.RR'),'FFA_CTL',to_date('19.02.21','DD.MM.RR'),'Инфо');
Insert into LOG_LEVEL (LOG_LEVEL,LOG_LEVEL_NO,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,LOV_LEVEL_NAME) values ('DEBUG','10','FFA_CTL',to_date('26.03.20','DD.MM.RR'),'FFA_CTL',to_date('19.02.21','DD.MM.RR'),'Отладка');
