CREATE OR REPLACE FORCE VIEW "OFSAA1"."DIM_COMMON_COA_BANK_LEAF_V" ("LEAF_COST_CENTRE_CD", "BANK_ID", "D_START_DATE", "D_CLOSE_DATE")
                                                                                                                                                   AS
WITH BNK_LEAF_HIER (BGN_COST_CENTRE_CD, N_COST_CENTRE_CD, N_PARENT_COST_CENTER_CD, D_START_DATE , D_CLOSE_DATE, N_NODE_TYPE_CD, N_LEGAL_ENTITY_CD) AS
  (SELECT N_COST_CENTRE_CD BGN_COST_CENTRE_CD ,
    N_COST_CENTRE_CD ,
    N_PARENT_COST_CENTER_CD ,
    D_START_DATE ,
    D_CLOSE_DATE ,
    N_NODE_TYPE_CD ,
    N_LEGAL_ENTITY_CD
  FROM FSDW.FSW_ORG_COST_CENTRE_MASTER
  WHERE N_NODE_TYPE_CD = 7
  UNION ALL
  SELECT CHLD.BGN_COST_CENTRE_CD BGN_COST_CENTRE_CD ,
    PRNT.N_COST_CENTRE_CD ,
    PRNT.N_PARENT_COST_CENTER_CD ,
    GREATEST ( PRNT.D_START_DATE, CHLD.D_START_DATE ) D_START_DATE ,
    LEAST ( PRNT.D_CLOSE_DATE, CHLD.D_CLOSE_DATE ) D_CLOSE_DATE ,
    PRNT.N_NODE_TYPE_CD ,
    PRNT.N_LEGAL_ENTITY_CD
  FROM BNK_LEAF_HIER CHLD
  JOIN FSDW.FSW_ORG_COST_CENTRE_MASTER PRNT
  ON ( CHLD.N_PARENT_COST_CENTER_CD = PRNT.N_COST_CENTRE_CD
  AND ( CHLD.D_START_DATE, CHLD.D_CLOSE_DATE ) overlaps ( PRNT.D_START_DATE, PRNT.D_CLOSE_DATE )
  AND PRNT.N_COST_CENTRE_CD != PRNT.N_PARENT_COST_CENTER_CD )
  )
SELECT DISTINCT FIRST_VALUE(BGN_COST_CENTRE_CD) OVER (PARTITION BY N_LEGAL_ENTITY_CD, D_START_DATE ORDER BY LENGTH(TO_CHAR(BGN_COST_CENTRE_CD))) BGN_COST_CENTRE_CD,
  N_LEGAL_ENTITY_CD ,
  D_START_DATE ,
  D_CLOSE_DATE
FROM bnk_leaf_hier
WHERE N_NODE_TYPE_CD = 2;