alter session set current_schema = odi_repo;
 

ALTER TABLE "SNP_SESS_TASK_LOG" DISABLE CONSTRAINT "FK_SESS_TASK_LOG";
ALTER TABLE "SNP_SESS_STEP_LV" DISABLE CONSTRAINT "FK_SESS_STEP_LV";
ALTER TABLE "SNP_SESS_TASK_LS" DISABLE CONSTRAINT "FK_SESS_TASK_LS";
ALTER TABLE SNP_STEP_REPORT DISABLE CONSTRAINT FK_STEP_REPORT; 
ALTER TABLE SNP_STEP_REPORT DISABLE CONSTRAINT FK_STEP_REPORT;

ALTER TABLE SNP_PARAM_SESS DISABLE CONSTRAINT FK_PARAM_SESS;
ALTER TABLE SNP_SESS_TASK DISABLE CONSTRAINT FK_SESS_TASK3;
ALTER TABLE SNP_SESS_STEP DISABLE CONSTRAINT FK_SESS_STEP;
ALTER TABLE SNP_VAR_SESS DISABLE CONSTRAINT FK_VAR_SESS;
ALTER TABLE SNP_SCHEDULE_EXEC DISABLE CONSTRAINT FK_CURRENT_SESSION;
ALTER TABLE SNP_STEP_LOG DISABLE CONSTRAINT FK_STEP_LOG;

TRUNCATE TABLE SNP_SESS_TASK_LS;

TRUNCATE TABLE SNP_SESS_TASK_LOG;

TRUNCATE TABLE SNP_STEP_LOG;

TRUNCATE TABLE SNP_SESS_STEP_LV;

TRUNCATE TABLE SNP_STEP_REPORT drop storage;

truncate table SNP_SCEN_REPORT;

truncate table SNP_SESSION; 

TRUNCATE TABLE SNP_PARAM_SESS;

TRUNCATE TABLE SNP_SESS_TASK;

TRUNCATE TABLE SNP_SESS_STEP;

truncate table SNP_VAR_DATA;

ALTER TABLE "SNP_SESS_TASK_LOG" ENABLE CONSTRAINT "FK_SESS_TASK_LOG";
ALTER TABLE "SNP_SESS_STEP_LV" ENABLE CONSTRAINT "FK_SESS_STEP_LV";
ALTER TABLE "SNP_SESS_TASK_LS" ENABLE CONSTRAINT "FK_SESS_TASK_LS";
ALTER TABLE SNP_STEP_REPORT ENABLE CONSTRAINT FK_STEP_REPORT; 
ALTER TABLE SNP_PARAM_SESS ENABLE CONSTRAINT FK_PARAM_SESS;
ALTER TABLE SNP_SESS_TASK ENABLE CONSTRAINT FK_SESS_TASK3;
ALTER TABLE SNP_SESS_STEP ENABLE CONSTRAINT FK_SESS_STEP;
ALTER TABLE SNP_VAR_SESS ENABLE CONSTRAINT FK_VAR_SESS;
ALTER TABLE SNP_SCHEDULE_EXEC ENABLE CONSTRAINT FK_CURRENT_SESSION;
ALTER TABLE SNP_STEP_LOG ENABLE CONSTRAINT FK_STEP_LOG;
 


 

